version: "3.8"

services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: calendar
    ports:
      - 3306:3306
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test:
        ["CMD", "mysqladmin", "ping", "-h", "localhost", "--password=password"]
      timeout: 30s
      retries: 10

  app:
    build: .
    ports:
      - 3000:3000
    environment:
      NODE_ENV: prod
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  dbdata:
